### ISSUE TITLE
Submodels with no reactions or no propensity generate a large number of events

### ISSUE THREAD

**Issue by jonrkarr** [KarrLab/wc_sim#29]

**Comment by artgoldberg** [comment]
Now Submodels with no reactions are not constructed. SSA submodels with propensity == 0 are handled by 2 cases:
1) if the SSA submodel is the entire simulation, schedule a noop event for it at time infinity
2) otherwise, have the SSA simulation wait, because other submodels can change the populations of its reactants
Naturally, more sophisticated algorithms for this are possible.
