### ISSUE TITLE
Sample from new distributions of initial conditions

### ISSUE THREAD

**Issue by jonrkarr** [KarrLab/wc_sim#41]
- DistributionInitConcentration.mean, DistributionInitConcentration.std
- Compartment.mean_init_volume, Compartment.std_init_volume

**Comment by jonrkarr** [comment]
- **Volume:** done in 3bc193b07f117252d309b48babab56210dc8c05b
- **Species counts:** still to do

**Comment by artgoldberg** [comment]
initialization done
refactoring and renaming to be considered

**Comment by artgoldberg** [comment]
WRT "It would best to refactor the initialization of simulation state so that it is separate from the construction of simulation objects. This will allow the establishment of the object graph in the construction of the objects and then initialization of simulation state using the object graph", I see your point.

However, in my implementation I addressed this issue by partially initializing 
some dynamical objects, like `DynamicCompartment`s and the species populations accessed by `DynamicSpecies`s, before creating the remaining dynamic objects and preparing them for simulation. Thus this refactoring isn't urgent now and I'm moving it to a new issue.
